all:
	gcc -o server -g server.o 
    gcc -g -o serverA serverA.c
    gcc -g -o serverB serverB.c
    gcc -g -o serverC serverC.c
    gcc -g -o serverD serverD.c
    gcc -g -o client client.c

clean:
    rm -f *.o 
